baseURL = "https://srinivasreddy.dev"
title = "Srini's blog"

theme = "hugo-coder"

languageCode = "en"
defaultContentLanguage = "en"

canonifyurls = true
paginate = 20
pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Srinivas Reddy Thatiparthy"
    gravatar = "thatiparthysreenivas@gmail.com"
    description = "Srini's personal website"
    footerContent = "All the content here is licensed under creative commons."
    info = "Python, Rust and independent consultant"
    keywords = "Blogger, Developer, Wannabe enterprenuer"

    dateFormat = "January 2, 2006"

    hideCopyright = false
    hideCredits = false
    since = 2019


    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS

    custom_css = []
    # Custom JS
    custom_js = []

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[[params.social]]
    icon = "fa fa-github"
    name = "Github"
    url = "https://github.com/srinivasreddy/"
    weight = 1
[[params.social]]
    icon = "fa fa-linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/srinivas-reddy-thatiparthy/"
    weight = 2
[[params.social]]
    icon = "fa fa-stack-overflow"
    name = "Stackoverflow"
    url = "https://stackoverflow.com/users/201393/srinivas-reddy-thatiparthy"
    weight = 3

[languages]
    [languages.en]
        languageName = "English"

    [[languages.en.menu.main]]
        name = "About"
        url = "about/"
        weight = 1

    [[languages.en.menu.main]]
        name = "Blog"
        url = "posts/"
        weight = 2

    [[languages.en.menu.main]]
        name = "Projects"
        url = "projects/"
        weight = 3

    [[languages.en.menu.main]]
        name = "Contact me"
        url = "contact/"
        weight = 4

    [[languages.en.menu.main]]
        name = "Hire me"
        url = "hireme/"
        weight = 5
